ingress:
  enabled: true
  host: "vaultwarden.kubernetes.local"
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: ca-secret
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: "local-path"
