grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: ["grafana.kubernetes.local"]
    path: /
    tls:
      - secretName: ca-secret
  persistence:
    enabled: true
    type: pvc
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    size: 15Gi
prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: ["prometheus.kubernetes.local"]
    tls:
      - secretName: ca-secret
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
